### ISSUE TITLE
HLTB API again completely changed, now using JSON

### ISSUE THREAD

**Issue by brainbaking** [danbush/hltb-alfred-workflow#4]
Hi, 

See https://github.com/ckatzorke/howlongtobeat/issues/40 
Scraping won't be needed anymore, but I'm afraid a bit of shuffling around will be. 

Again, happy to help if required!

**Comment by danbush** [comment]
Thanks for flagging! I [started a branch](https://github.com/danbush/hltb-alfred-workflow/tree/2022-api-update) where I started figuring things out. doesn't work yet though

**Comment by danbush** [comment]
Should be fixed now!

**Comment by brainbaking** [comment]
Excellent!! Thanks!
